apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: skyline-parameter-store
  namespace: skyline
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
