apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skyline-db-secret
  namespace: skyline
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: skyline-parameter-store
  target:
    name: skyline-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /skyline-system-demo/demo/database/host
    - secretKey: DB_PORT
      remoteRef:
        key: /skyline-system-demo/demo/database/port
    - secretKey: DB_NAME
      remoteRef:
        key: /skyline-system-demo/demo/database/name
    - secretKey: DB_USER
      remoteRef:
        key: /skyline-system-demo/demo/database/username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /skyline-system-demo/demo/database/password
