apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: skyline-system-demo-eks
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  features:
    admissionController:
      enabled: true

    clusterChecks:
      enabled: true

    orchestratorExplorer:
      enabled: true

    logCollection:
      enabled: true
      containerCollectAll: false

    apm:
      instrumentation:
        enabled: true
        targets:
          - name: default-target
            ddTraceVersions:
              java: "1"